IF(WIN32)
	FIND_PROGRAM(FDB_ISQL isql)

	SET(Fbembed_FOUND 1)
	SET(FBEMBED_INCLUDE_DIR "")
	SET(FBEMBED_LIBRARY "")
ELSE(WIN32)
	FIND_PROGRAM(FDB_ISQL isql-fb-2.0)
	
	FIND_PATH(FBEMBED_INCLUDE_DIR ibase.h PATHS /usr/include /usr/local/include)
	FIND_LIBRARY(FBEMBED_LIBRARY NAMES fbembed)
	
	IF(FBEMBED_INCLUDE_DIR AND FBEMBED_LIBRARY)
	  SET(Fbembed_FOUND 1)
	  message(STATUS "Found fbembed: ${FBEMBED_LIBRARY}")
	ELSE(FBEMBED_INCLUDE_DIR AND FBEMBED_LIBRARY)
	  SET(Fbembed_FOUND 0 CACHE BOOL "Not found fbembed library")
	  message(STATUS "NOT Found fbembed, disabling it")
	ENDIF(FBEMBED_INCLUDE_DIR AND FBEMBED_LIBRARY)
	MARK_AS_ADVANCED(FBEMBED_INCLUDE_DIR FBEMBED_LIBRARY)
ENDIF(WIN32)


