

MESSAGE(STATUS "setting up Xmlbeansxx MACROS.")



MACRO(XMLBEANSXX_GEN XSD SRC_C SRC_H)
	SET(${XSD}_SRC ${CMAKE_CURRENT_BINARY_DIR}/${SRC_H} ${CMAKE_CURRENT_BINARY_DIR}/${SRC_C})
	SET(${XSD}_HEADER ${CMAKE_CURRENT_BINARY_DIR}/${SRC_H})
	ADD_CUSTOM_COMMAND(OUTPUT ${${XSD}_SRC}
		COMMAND ${XMLBEANSXX_GEN_PROG} ${CMAKE_CURRENT_SOURCE_DIR}/${XSD}
		DEPENDS generator ${XSD}
			
	)	
ENDMACRO(XMLBEANSXX_GEN)

MACRO(XMLBEANSXX_COPY SRC DEST)
	SET(${DEST}_FILE ${CMAKE_CURRENT_BINARY_DIR}/${DEST})
	ADD_CUSTOM_COMMAND(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${DEST}
		COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/${SRC} ${CMAKE_CURRENT_BINARY_DIR}/${DEST}
	)
ENDMACRO(XMLBEANSXX_COPY)
